[build-system]
requires = ["flit_core >= 3.12.0, <4"]
build-backend = "flit_core.buildapi"

[project]
version = "0.1.0"
name = "cautious-meme"
requires-python = ">= 3.13"
description = "Attempt at running whisper_large_v3_turbo locally."
readme = "README.md"
license = "BSD-3-Clause"
license-files = [ "LICENSE" ]
keywords = [ "whisper", "local-test" ]
classifiers = [
 "Development Status :: 3 - Alpha"
]
dependencies = [
	"transformers>=5.7.0",
	"torch>=2.11.0",
	"pandas>=3.0.2",
	"numpy>=2.4.4"
]

[project.urls]
Repository = "https://github.com/rustle003/cautious-meme.git"

[project.scripts]
download_model = "cautious_meme.model_downloader:model_downloader.orchestrate_model_download"

[tool.flit.sdist]
exclude = ["src/cautious_meme/models/*"]