[[model-repo]]
repo_id = "openai/whisper-large-v3-turbo"
download_path = "../models/openai/whisper-large-v3-turbo"
repo-provider = { provider = "huggingface", dependencies = ["huggingface_hub==1.13.0"] }

#[[model-repo.repo-provider]]
#provider = "huggingface"
#dependencies = ["huggingface_hub==1.13.0"]
